name: Build Deploy and SonarQube

on:
  workflow_dispatch:

jobs:

  build:
    name: Build and Deploy
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Install Maven
        run: sudo yum install maven -y

      - name: Build WAR
        run: mvn -B clean package

      - name: Deploy WAR to Tomcat
        env:
          TOMCAT_URL: ${{ secrets.TOMCAT_URL }}
          TOMCAT_USER: ${{ secrets.TOMCAT_USER }}
          TOMCAT_PASSWORD: ${{ secrets.TOMCAT_PASSWORD }}

        run: |
          WAR=$(ls target/*.war | head -n 1)

          echo "WAR FILE: $WAR"
          echo "Deploying to: $TOMCAT_URL"

          curl -v -u "${TOMCAT_USER}:${TOMCAT_PASSWORD}" \
          --upload-file "$WAR" \
          "${TOMCAT_URL}/manager/text/deploy?path=/ecommerce-app&update=true"



    
  sonarqube:
    name: SonarQube Analysis
    runs-on: self-hosted
    needs: build

    steps:
      - name: Clear Sonar Cache
        run: rm -rf ~/.sonar/cache

      - name: Run SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

        run: |
          mvn sonar:sonar \
          -Dsonar.projectKey=ecommerce-app \
          -Dsonar.host.url=$SONAR_HOST_URL \
          -Dsonar.login=$SONAR_TOKEN
  security-check:
    runs-on: self-hosted
    needs: sonarqube
    steps:
      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin

      - name: Trivy FS Scan
        run: trivy fs --format table -o fs-report.json .
  docker-build:
    runs-on: self-hosted
    needs: security-check
    steps:
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.Docker_Repository }}:${{ github.sha }} .
      - name: Run Docker Container
        run: |
          docker run -d \
           --name my_app_container \
           -p 8080:8080 \
           ${{secrets.Docker_Repository}}:${{github.sha}} 